### ISSUE TITLE
TestTransactionLogs.startTransactionLogMessageWithRandomProcessData fails sometimes non-deterministically

### ISSUE THREAD

**Issue by dheldt** [konfidas/TTC#53]
For some reason, the test TestTransactionLogs.startTransactionLogMessageWithRandomProcessData fails sometimes. We have to invastigate why this is the case and fix it. I assume, the test creates random process data, that is to long for the code to handle:

```
java.lang.IllegalArgumentException: 16777221 > 9615421

	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4029)
	at de.konfidas.ttc.messages.LogMessageImplementation.getEncodedValue(LogMessageImplementation.java:187)
	at de.konfidas.ttc.messages.TransactionLogMessage.parseProcessData(TransactionLogMessage.java:155)
	at de.konfidas.ttc.messages.TransactionLogMessage.parseCertifiedData(TransactionLogMessage.java:101)
	at de.konfidas.ttc.messages.LogMessageImplementation.parse(LogMessageImplementation.java:212)
	at de.konfidas.ttc.messages.LogMessageImplementation.<init>(LogMessageImplementation.java:92)
	at de.konfidas.ttc.messages.TransactionLogMessage.<init>(TransactionLogMessage.java:85)

```

**Comment by nils-tekampe** [comment]
Problem lays in 
https://github.com/konfidas/TTC/blob/a0548705b775fe71b0d95dc369d164da9737662b/src/main/java/de/konfidas/ttc/messages/LogMessageImplementation.java#L180

The length shall be unsigned but its currently read as a signed integer. Negative values will lead to the error.

**Comment by dheldt** [comment]
`return new BigInteger(1,lengthBytesFromElement).intValue();`

does the trick...

**Comment by nils-tekampe** [comment]
Fixed now :-)
